### ISSUE TITLE
Pitch de présentation

### ISSUE THREAD

**Issue by WilsonUCA** [Gestion-de-projet-M1-A-R/Gestion-de-projet-Org#1]
Durée 3 minutes. Vous présentez en groupe :

- Le thème du jeu
- Le type de jeu
- Pour quels joueurs
- Par quels animateurs
- Les objectifs : qu'est ce qu'on apprend dans le jeu + objectifs pédagogiques

**Comment by theresia-sall** [comment]
https://docs.google.com/document/d/1iBSVIu3peST4FknHb8Sjy_jyo2gTu42LkzRSObIV8SM/edit?usp=sharing

**Comment by WilsonUCA** [comment]
Theme du jeu : Sensibilisation aux handicaps du trouble de vue (personne non voyante ou mal voyante / )
Le type du jeu : mise en situation: 
     Réaliser certaines actions du quotidien avec les yeux bandés, ou des lunettes floue. Mettre en jeu le toucher, l'ouïe,...
Trouver des situations où les autres sens sont importants mais passe après la vue (ressenti du vent d'un ventilateur pour le situer,...)
Objectifs : sensibilisation aux réalités quotidiennes des personnes non / mal voyantes
    Challenger les capacités cognitives et Mettre en valeur celles des personnes en situation de handicap qui réalisent ces actions quotidiennement 
Age : à partir de 7 ans (jeu inclusif)
     Avoir un minimum de recule pour éduquer sur le handicap
Animateur : personne formée (handicap ou jeunesse) ou non formée avec une fiche (mise en place d'un livre ou manuel pour expliquer le jeu)

**Comment by moounally** [comment]
**1re version du pitch** 👍🏻
T’as déjà fermé les yeux pour faire genre t’es concentré ? Eh bien, garde-les fermés et essaye de survivre… dans un monde où tu verras bien que tu verras rien, mais où tout compte. Spoiler : ça va être drôle… enfin, pour nous !

Bienvenue dans 'T’as Pas Vu Venir', un jeu qui te plonge littéralement dans l’obscurité. Ici, pas d’écran, pas de cheat code, pas de lumière. On te met dans la peau d’une personne malvoyante ou aveugle pour te faire découvrir leur quotidien, leurs défis… et leur incroyable capacité à s’adapter.

C’est pour qui ? Pour tout le monde : les jeunes qui adorent les défis, les adultes curieux, les entreprises qui veulent sensibiliser leurs équipes. Si t’as des yeux, ce jeu est pour toi.

C’est quoi le but ? Comprendre qu’on ne voit pas qu’avec les yeux. Chaque défi te pousse à écouter, ressentir, réfléchir autrement. Tu vas rigoler, galérer, et surtout, apprendre à voir le monde d’un autre point de vue.

Comment on joue ? On te prive de ta vue. T’as des missions simples : marcher, résoudre des énigmes, trouver des objets, ou même socialiser… sans jamais ouvrir les yeux. Spoiler : c’est plus dur que de trouver ton téléphone sous ton lit.

Et pourquoi ? Parce qu’on veut changer ton regard sur le handicap visuel. On veut que tu sortes de là plus empathique, plus attentif, et peut-être un peu moins râleur. Parce que comprendre les défis d’un autre, c’est le premier pas pour changer les choses.

Alors, t’as les tripes de fermer les yeux et de plonger dans le noir total ? Attention, ce jeu risque de te marquer… et pas juste parce que tu risques de te prendre un mur.
