### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by WilsonUCA** [Gestion-de-projet-M1-A-R/Gestion-de-projet-Org#15]
Fiche Gamae
ressources mises en page
tutoriel joueur : présentation du jeu, les étapes, les objectifs, sécurités, conseils

fiche animateur

**Comment by theresia-sall** [comment]
https://studentaffairs.vancouver.wsu.edu/access-center/etiquette-interacting-people-who-are-blind-who-have-low-vision

**Comment by theresia-sall** [comment]
https://excitingescapes.co.uk/blog/are-escape-rooms-accessible-for-disabled-people/
